### ISSUE TITLE
Proposal: archive this repo

### ISSUE THREAD

**Issue by cknoll** [klim-/pyplane#7]
The PR #6 triggers the following thought: imho it would be sensible to define https://github.com/tud-RST/pyplane/ as the canonical repo for pyplane. Of course it emerged as a project of @klim-. However, I think now it is more a project of the institute as a whole. That would also avoid potential confusion which repo is the "correct" one for new users (e.g. our students): the original one or the fork.

I suggest the following:

1. Making a (final) commit to the master branch of this repo announcing that the project is continued as https://github.com/tud-RST/pyplane/ prominently at the top of the README and then archive this repo here.

2. At https://github.com/tud-RST/pyplane/ we can then remove the "fork-property" to avoid confusion.

We can also add a *History* section to the README that the project was started by @klim- (if desired).

What do you mean @jcwinkler @klim-?

**Comment by jcwinkler** [comment]
I agree with @cknoll's proposal.
